django_examples/hello_django/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("posts/<int:id>", views.PostDetailView.as_view(), name="details"),

]

django_examples/hello_django/books/urls.py
from django.urls import path

from . import views

app_name = "books"
urlpatterns = [
    path("", views.BookListView.as_view(), name="list"),
    path("create/", views.BookCreateView.as_view(), name="create"),
    path("<int:pk>/", views.BookDetailView.as_view(), name="details"),
]

django_examples/hello_django/hello_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("simplerouting.urls")),
    path("matematyka/", include("matematyka.urls")),
    path("blog/", include("blog.urls")),
    path("", include("templates_examples.urls")),
    path("", include("news.urls")),
    path("", include("modele.urls")),
    path("books/", include("books.urls")),

]

django_examples/hello_django/books/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    published_year = models.PositiveIntegerField()
    is_avilable = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

django_examples/hello_django/books/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from .models import Book

class BookListView(ListView):
    model = Book


class BookDetailView(DetailView):
    model = Book

class BookCreateView(CreateView):
    model = Book
    fields = ["title", "author", "published_year", "is_avilable"]
    success_url = reverse_lazy("books:list")

django_examples/hello_django/books/templates/books/book_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Szczegoly ksiażki</h1>

    <h2>{{ book.title }}</h2>
    <h3>{{ book.author }}</h3>
    <h4>{{ book.published_year }}</h4>

{% endblock content %}

django_examples/hello_django/books/templates/books/book_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Utworz ksiazke</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit">Dodaj</button>
    </form>
{% endblock content %}

django_examples/hello_django/books/templates/books/book_list.html
{% extends "base.html" %}
{% block content %}
    <h1>Lista ksiażek</h1>
    {% for book in book_list %}
        <h2><a href="{% url 'books:details' book.id %}">{{ book.title }}</a></h2>
    {% endfor %}
{% endblock content %}