django_examples/hello_django/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path("", views.PostListView.as_view(), name="list"),
    path("posts/<int:id>", views.PostDetailView.as_view(), name="details"),

]

django_examples/hello_django/hello_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("simplerouting.urls")),
    path("matematyka/", include("matematyka.urls")),
    path("blog/", include("blog.urls")),
    path("", include("templates_examples.urls")),
    path("", include("news.urls")),
    path("", include("modele.urls")),
    path("books/", include("books.urls")),

]

django_examples/hello_django/news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('news/', views.news_list, name='list'),
    path('news/<int:pk>/', views.news_detail, name='detail'),
    path("news/author/add", views.author_add, name='author_add'),
]

django_examples/hello_django/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>
            {% block title %}{% endblock %}
        </title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
              rel="stylesheet">
        {% block extra_style %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <header>
                <h1>ALX</h1>
                <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
                    <div class="container-fluid">
                        <ul class="nav">
                            <li class="nav-item">
                                <a class="nav-link active" href="/">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url "blog:list" %}">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'news:list' %}">News</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle"
                                   href="#"
                                   role="button"
                                   data-bs-toggle="dropdown">Dropdown</a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" href="#">Link</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="#">Another link</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="#">A third link</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="javascript:void(0)">About</a>
                            </li>
                            <li class="nav-item ali">
                                <a class="nav-link" href="javascript:void(0)">XXX</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav ms-auto">
                            <li class="nav-item">{% include 'includes/user_info.html' %}</li>
                        </ul>
                    </div>
                </nav>
            </header>
            {% if messages %}
                <div class="container mt-3">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show"
                             role="alert">
                            {{ message }}
                            <button type="button"
                                    class="btn-close"
                                    data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                        </div>
                    {% endfor %}
                </div>
            {% endif %}
            {% block content %}
            {% endblock content %}
            <footer>
                <div>Redakcja to: {{ redakcja }}</div>
                <div>
                    <ul>
                        <li>Postów: {{ posts_count }}</li>
                        <li>Newsów: {{ news_count }}</li>
                        <li>Autorów: {{ authors_count }}</li>
                    </ul>
                </div>
            </footer>
        </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>